### PR TITLE
Improve error reporting

### LINKED ISSUE #86: Page Error reporting
For `build.mjs`, line 306-8:

```
/* refuse to render if there are page errors */
      if (listEvents().length)
        throw new Error(`Page has errors`);
```

This causes full stop, making de-bugging errors difficult. Suggest pushing the errors in `listEvents` to the `Error` message. Currently easiest workaround is the remove lines 307-8 and let page render with error message on page.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #86

### CODE REVIEW

**Comment by SteveLLamb** [comment]
It's not even getting to the error messages. I just tested with a dead link and no table captions, and this was the output:

```
$ node scripts/build.mjs
Current branch: issues/0086-improve-error-reporting
Current commit hash: 6da54f3e4c6fb807b3ea1326437666d80387a15a
Rendering the document at file:///.../html-pub/doc/main.html?buildHash=6da54f3e4c6fb807b3ea1326437666d80387a15a
Error: Evaluation failed: Error: Page has errors
    at pptr://__puppeteer_evaluation_script__:15:15
    at ExecutionContext._ExecutionContext_evaluate (file:///.../html-pub/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:225:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///.../html-pub/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:104:16)
    at async render (file:///.../html-pub/scripts/build.mjs:296:5)
    at async build (file:///.../html-pub/scripts/build.mjs:170:23)
    at async main (file:///../html-pub/scripts/build.mjs:432:3)
```

**Comment by palemieux** [comment]
Thanks for checking. See improved error reporting.

**Comment by SteveLLamb** [comment]
> Thanks for checking. See improved error reporting.

That's not reporting on the CL:
```
Table is missing a caption
Anchor points to non-existent href
```

Not to be nitpicky about it, but if i remove that section of the build, the errors render on the page directly with links to the specific errors (to help find them):
```
Table is missing a caption ([link](https://github.com/SMPTE/html-pub/pull/94#tab-body-structure))
Anchor points to non-existent href ([link](https://github.com/SMPTE/html-pub/pull/94#739840592))
```
Any way we can pass that info into the CL message as well? Or maybe not stop on error and still render the page so user can see what needs to be fixed?

**Comment by palemieux** [comment]
The links are not useful since they (often) refer to dynamically-generated IDs.

The user should never push something that has errors, so in what circumstance would the user need to go through the github workflow log?

**Review by SteveLLamb — APPROVED** [review]

**Pull request merged**
