### PR TITLE
Add support for equations

### LINKED ISSUE #31: Add support for equation linking and numbering
Breaking to its own issue with v2 milestone from #7, as other items are resolved, and this is not important for v1.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #31

### CODE REVIEW

**Comment by palemieux** [comment]
@ERyan71258 Let me know what you think: https://doc.smpte-doc.org/html-pub/feature/add-support-equations/#sec-equations

**Comment by SteveLLamb** [comment]
You took out the prose for section 7.2.13. Do you miss taking out the header as well or left it blank intentionally?

Screen Shot 2023-06-26 at 10 13 48 AM

**Review by SteveLLamb — APPROVED** [review]

**Comment by palemieux** [comment]
> You took out the prose for section 7.2.13. Do you miss taking out the header as well or left it blank intentionally?

Where do you see that change?

**Comment by SteveLLamb** [comment]
> Where do you see that change?

On redline against most recent edition.

**Comment by palemieux** [comment]
> On redline against most recent edition.

That includes changes outside of this PR.

**Pull request merged**
