### PR TITLE
Improve the engineering document front matter

### LINKED ISSUE #158: Make the state and stage of the document more obvious
The stage (WD, CD, FCD...) and the status (approved, draft) should be more obvious:

- the stage of the document should be larger and spelled out
- the "not-yet-published" box notice should be before the ToC
- draft documents should be labeled "not approved"

image

image

### PR DESCRIPTION
**Pull request by palemieux**
Closes #158 

See example at https://github.com/SMPTE/html-pub-template/pull/14

### CODE REVIEW

**Review by SteveLLamb — APPROVED** [review]

**Comment by SteveLLamb** [comment]
How about a "pubPublic" boolean flag that will only be available (presently) with a CD, that would trigger rendering "Public" in the header?

**Comment by palemieux** [comment]
> How about a "pubPublic" boolean flag that will only be available (presently) with a CD, that would trigger rendering "Public" in the header?

See flag rendered at https://github.com/SMPTE/html-pub-template/pull/14

**Review by SteveLLamb — APPROVED** [review]

**Comment by palemieux** [comment]
> The link [SMPTE/html-pub-template#14](https://github.com/SMPTE/html-pub-template/pull/14) only shows Committee Draft without "public". Is that the expected behaviour?

Yes. "Public CD" is not a formal stage, but merely short-hand to mean a Committee Draft that has been approved for public distribution by the SVP.

**Comment by tbause** [comment]
That is contrary to what was previously decided in ST to clearly mark a document as public CD see (see PCD coversheet). We can discuss on Friday. I my view this needs a ST decision to reverse.

**Comment by palemieux** [comment]
> That is contrary to what was previously decided in ST to clearly mark a document as public CD

I do not recall such a decision, and do not see such a requirement in AG 22.

In fact AG 22 gives the Director of Standards the responsibility of coming up with the presentation of Public CDs:

https://doc.smpte-doc.org/ag-22/main/#sec-availability

**Comment by tbause** [comment]
With all due respect, I do remember and hence I did the work to add the cover page to all past PCDs. In fact, I was opposed to do the additional work it takes but ST/SVP insisted. It did not matter at the time that the form of publication was my decision, as you point out. In my recollection the cover page was reviewed by ST as well. Exactly for that reason I want ST to approve any new form of publication of PCDs. I do think that the PCD document should be clearly marked as public CD to differentiate them from CDs which are not public. It should also clearly state the patent and licensing provisions as shown in AG-22 in case the document is viewed outside of the context of repository (e.g. downloaded PDF or printed HTML page).

**Comment by palemieux** [comment]
> I do think that the PCD document should be clearly marked as public CD to differentiate them from CDs which are not public. 

Yes, the CONFIDENTIAL statement in the front matter makes that obvious.

>  It should also clearly state the patent and licensing provisions as shown in AG-22 in case the
> document is viewed outside of the context of repository (e.g. downloaded PDF or printed HTML page).

Can you specify what is missing from the front matter?

**Comment by tbause** [comment]
BTW, the ST meeting minutes from May/June 2020 do mention the "Discussion on look & process of Public CD document" and "A public CD should pass through publishing SMPTE QC. The resulting document should become the new master - Action: SVP & DoS to update AG-22 with a mechanism". The "... Action: SVP & DoS to update AG-22 ..." never happened. The referenced review documents are not accessible because the resided on now defunct OLC.

**Comment by tbause** [comment]
"Can you specify what is missing from the front matter?"

Basically, what's on the PCD coversheet which is mainly the text mandated by AG-22 in Annex C.

**Comment by palemieux** [comment]
> Basically, what's on the PCD coversheet which is mainly the text mandated by AG-22 in Annex C.

_C.1 Contributor License Agreement (CLA) notice_ is only relevant to the GitHub repo, where the public can contribute, and not relevant to the document itself, since the public cannot contribute to the document.

_C.2 Copyright notice_ is reflected in the document as follows:

image

_C.3 Patent notice_ is reflected in the document using the usual SMPTE disclaimer:

image

**Comment by palemieux** [comment]
> Basically, what's on the PCD coversheet 

The notice about the draft nature of the work is reflected in the document as follows:

image

**Comment by palemieux** [comment]
Some cover pages have a link to all of the SMPTE public CDs, but:

1. this is not required by AG-22
2. what is the purpose of that link? shouldn't there be a link to *all* SMPTE documents?
3. a link where to file issues would be more useful

**Comment by SteveLLamb** [comment]
@tbause can this be resolved so that we may continue on with the PCDs we have incoming as planned?

**Review by tbause — APPROVED** [review]

**Pull request merged**
