### PR TITLE
Add support for table numbering

### PR DESCRIPTION
**Pull request by palemieux**

### CODE REVIEW

**Comment by SteveLLamb** [comment]
Per ISO guidelines, need to account for:
`In annexes, the table numbering restarts and the number is preceded by the annex letter (e.g. Table A.1).`

Many of our docs follow this.

**Comment by palemieux** [comment]
Yes. What is your feeling on the relevance of this in the age of electronic documents?

**Comment by SteveLLamb** [comment]
> Yes. What is your feeling on the relevance of this in the age of electronic documents?

If we have to make "hard copies" of these docs to take to ISO (like planned with all the 21DC docs) we have to follow this. I'd rather not have to hand edit an "ISO conformed" version.

**Comment by palemieux** [comment]
@SteveLLamb Check the revised Annex table numbering scheme.

**Comment by SteveLLamb** [comment]
> @SteveLLamb Check the revised Annex table numbering scheme.

Looks good. I updated the table ids to remove numbers (same way sections are done).

**Review by SteveLLamb — APPROVED** [review]

**Pull request merged**
